import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";

import Hero from "/public/src/img/hero.png";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>HustleX</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />

				<link
					rel="preload"
					href="/public/IntegralCF-ExtraBold.otf"
					as="font"
					crossOrigin=""
				/>

				<link
					rel="preload"
					href="/public/IntegralCF-Bold.otf"
					as="font"
					crossOrigin=""
				/>
			</Head>

			<nav className="navbar">
				<ul className="nav-list">
					<div className="logo">
						<a href="/">
							<img src="/public/img/logo.png" alt="" />
						</a>
					</div>
					<li>
						<a href="#home">Home</a>
					</li>
					<li>
						<a href="#subhero">Features</a>
					</li>
					<li>
						<a href="#subhero">Team</a>
					</li>
					<li>
						<a href="#footer">Contact Us</a>
					</li>
				</ul>
				<div className="burger">
					<div className="line"></div>
					<div className="line"></div>
					<div className="line"></div>
				</div>
			</nav>

			{/* home section */}
			<section className="home" id="home">
				<div className="content">
					<h1>Social Fitness</h1>
					<p>
						Personalized AI Workouts. Meet people <br /> Earn rewards. Compete
						with friends.
					</p>
					<a href="#register" className="btn">
						<h3 className="btntxt">PRE-REGISTER</h3>
						<div></div>
					</a>
				</div>
				{/* <img src={Hero} className="homeimg" /> */}
				<Image src="/img/hero.png" layout="fill" />
			</section>

			<section className="subhero">
				<div data-aos="fade-right" className="subheroleft">
					<h1>
						Hustle <br /> Meet
					</h1>
					<h3>
						Hustle <br /> Meet
					</h3>
					<h2>
						HustleX is the first of its kind app which lets you find people that
						are into the same things as you, be it yoga, running, or even just
						meeting for a cup of coffee.
					</h2>
				</div>
				<img data-aos="fade-left" src="/img/event.png" alt="events" />
			</section>

			{/* Custom Workout */}
			<section className="subhero" id="subhero">
				<div data-aos="fade-right" className="subheroleft">
					<h1>
						Hustle <br /> Workout
					</h1>
					<h3>
						Hustle <br /> Workout
					</h3>
					<h2>
						AI-powered workout builder which lets you build your own
						personalized workout in a jiffy.
					</h2>
					<p>
						{" "}
						No more hours spent on browsing through hundreds of exercises and
						looking for suitable variations for every day - create your workout
						and get started in minutes with it!
					</p>
				</div>
				<img data-aos="fade-left" src="/img/custom.png" alt="" />
			</section>

			{/* rewards section */}
			<section className="subhero alt">
				<div data-aos="fade-right" className="subheroleft">
					<h1>Rewards</h1>
					<h3>Rewards</h3>
					<h2>
						Every time you do something on HustleX, you receive Hustle coins.
						you can use these coins to get exclusive rewards.
					</h2>
					<p>
						{" "}
						It's simple, every time you do something on HustleX, you receive
						Hustle coins. Use these coins to unlock exclusive and exciting
						rewards that will make your life more interesting!
					</p>
				</div>
				<Image src="/img/reward.png" alt="rewards" layout="fill" />
			</section>

			<section className="register" id="register">
				<h1 className="registertext">PRE-REGISTER</h1>
				<h1 className="registersubtext">
					Get early access to our software, get access to beta release be part
					of the X club before anyone else{" "}
				</h1>
				<div className="form">
					<iframe
						src="https://docs.google.com/forms/d/e/1FAIpQLScZzjSRbFPP41egqPhwix1E9YQ_tc8G-_fmDbi7FfoUWiTVlw/viewform?embedded=true"
						width="100%"
						height="100%"
						frameBorder={0}
						marginHeight={0}
						marginWidth={0}
					>
						Loading…
					</iframe>
				</div>
			</section>

			<section className="footer" id="footer">
				<div className="footercontainer">
					<div className="contact">
						<h1 className="footertext">CONTACT</h1>
						<div className="social">
							<a target="_blank" href="https://www.instagram.com/hustlex.club/">
								<img src="https://img.icons8.com/office/50/000000/instagram-new.png" />
							</a>
							<a
								target="_blank"
								href="https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcSHvnzPLwfnXHplnZCrSxvcfFnVXvTkkzfNpSrWhJqfkjlVhZZhfnvbjBpKfNhGqjwFmDzDw"
								className="social"
							>
								<img src="https://img.icons8.com/color/48/000000/gmail-new.png" />
							</a>
						</div>
					</div>
					<div className="company">
						<h1 className="footertext">COMPANY</h1>
						<a href="" className="comp">
							<h1 className="linkstext">About</h1>
						</a>
						<a href="./pages/career" className="comp">
							<h1 className="linkstext">Work with US</h1>
						</a>
						<a
							href="https://www.behance.net/gallery/125116709/HustleX-Fitness-App-Branding"
							className="comp"
						>
							<h1 className="linkstext">Branding</h1>
						</a>
						<a href="./pitch-deck.pdf" className="comp">
							<h1 className="linkstext">Pitch Deck</h1>
						</a>
					</div>
					<div className="links">
						<h1 className="footertext">LINKS</h1>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
					</div>
					<div className="policies">
						<h1 className="footertext">POLICIES</h1>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
						<a href="" className="comp">
							<h1 className="linkstext">-</h1>
						</a>
					</div>
				</div>
				<div className="lowfootercointainer">
					<img src="/public/img/logo-light.png" alt="logo" />
					<h3>Made with ❤️ by HustleX Team in India</h3>
					<h3>© 2021, HUstleX Fitness</h3>
				</div>
			</section>
		</div>
	);
};

export default Home;
