import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from '../src/components/navBar'
import Hero from '../src/components/home'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Social Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Hero />
    </div>
  )
}

export default Home
